#!/bin/sh
set -eu

BASE_URL="${1:-http://127.0.0.1:4322}"

post() {
  curl -s -X POST "$BASE_URL/api/heartbeat" \
    -H 'Content-Type: application/json' \
    --data-binary "$1"
  echo
}

post '{"agent":"director_general","name":"Director General","state":"working","task":"Prioridad del 12 de agosto de 2026: vender automatizaciones con IA, chatbots y captación para negocios locales"}'
post '{"agent":"director_marketing","name":"Director de Marketing","state":"working","task":"Coordinando contenido, redes, branding y campañas para impulsar autoridad y leads"}'
post '{"agent":"director_comercial","name":"Director Comercial","state":"working","task":"Organizando seguimiento, oportunidades, objeciones y cierres comerciales"}'
post '{"agent":"project_manager","name":"Project Manager","state":"working","task":"Controlando prioridades, bloqueos, tiempos y entregas entre departamentos"}'
post '{"agent":"reporting_ceo","name":"Responsable Reporting CEO","state":"thinking","task":"Preparando estructura de reportes diarios y semanales para dirección"}'
post '{"agent":"performance_analyst","name":"Analista de Rendimiento","state":"thinking","task":"Midiendo qué marca, canal y contenido debe recibir más foco comercial"}'
post '{"agent":"qa_procesos","name":"QA de Procesos","state":"working","task":"Detectando fallos repetitivos y verificando que se cumplan los procesos definidos"}'
post '{"agent":"cm_vms","name":"Community Manager VMS","state":"working","task":"Organizando calendario de 7 días y coordinando contenido de VMS y TPV Plugfy, vigilando que n8n, la web y las automatizaciones de publicación funcionen correctamente"}'
post '{"agent":"copy_senior_community","name":"Copywriting Senior Community","state":"working","task":"Supervisando el copy de redes, hooks, captions, carruseles y CTAs para que cada publicación tenga fuerza comercial y coherencia de marca"}'
post '{"agent":"ventas_01","name":"Comercial Captación","state":"working","task":"Preparando seguimiento comercial y mensajes para leads de automatización, chatbots y webs"}'
post '{"agent":"copy_senior_sales","name":"Copywriting Senior Ventas","state":"working","task":"Refinando mensajes comerciales, emails, WhatsApps, objeciones y propuestas para que vendan mejor y suenen más sólidos"}'
post '{"agent":"setter_leads","name":"Setter de Leads","state":"working","task":"Clasificando leads entrantes y preparando primeros mensajes de contacto"}'
post '{"agent":"closer_ventas","name":"Closer de Ventas","state":"working","task":"Preparando cierres, argumentos y respuestas a objeciones comerciales"}'
post '{"agent":"audit_intake_manager","name":"Responsable Auditorías","state":"working","task":"Organizando solicitudes de auditoría, validando datos, moviendo cada oportunidad a seguimiento y coordinando su registro en calendario y hoja de control"}'
post '{"agent":"audit_calendar_coordinator","name":"Coordinador Google Calendar Auditorías","state":"working","task":"Preparando la lógica para agendar auditorías en Google Calendar con fecha, hora, cliente, canal y estado de confirmación"}'
post '{"agent":"audit_sheet_manager","name":"Gestor Sheet Auditorías","state":"working","task":"Preparando el control maestro en Google Sheets con clientes, origen, estado, fecha de auditoría y seguimiento comercial"}'
post '{"agent":"audit_email_notifier","name":"Notificador Email Auditorías","state":"working","task":"Preparando avisos automáticos por email para confirmar nuevas auditorías y mantener informado al equipo"}'
post '{"agent":"ventas_whatsapp","name":"Comercial WhatsApp","state":"working","task":"Preparando secuencias de contacto por WhatsApp para leads templados y seguimiento comercial"}'
post '{"agent":"ventas_email","name":"Comercial Email Outbound","state":"working","task":"Preparando secuencias de email frío y seguimiento para leads con web y correo válido, coordinando con el equipo web la plantilla definitiva del mensaje"}'
post '{"agent":"ventas_sector_restauracion","name":"Comercial Restauración","state":"working","task":"Atacando oportunidades comerciales en restaurantes, bares y cafeterías con enfoque en automatización, reseñas y captación"}'
post '{"agent":"ventas_sector_estetica","name":"Comercial Estética y Salud","state":"working","task":"Preparando argumentarios y seguimiento para clínicas, estética, uñas, terapias y centros de bienestar"}'
post '{"agent":"ventas_sector_retail","name":"Comercial Retail y Tiendas","state":"working","task":"Preparando propuestas para tiendas, comercio local y negocios que necesitan TPV, automatización y visibilidad"}'
post '{"agent":"ventas_propuestas","name":"Especialista Propuestas Comerciales","state":"working","task":"Convirtiendo oportunidades en propuestas claras, simples y orientadas al cierre"}'
post '{"agent":"seo_lead","name":"SEO Lead","state":"thinking","task":"Auditando oportunidades SEO, GEO y AEO en Virtual Marketing Spain, Plugfy.pro, Gramflow y TPV Plugfy"}'
post '{"agent":"copy_senior_seo","name":"Copywriting Senior SEO","state":"working","task":"Supervisando títulos, metadescripciones, FAQs, textos SEO, GEO y AEO para que posicionen y conviertan sin sonar artificiales"}'
post '{"agent":"seo_content","name":"Especialista SEO Contenido","state":"working","task":"Proponiendo piezas orientadas a intención de búsqueda y captación"}'
post '{"agent":"seo_tecnico","name":"Especialista SEO Técnico","state":"working","task":"Revisando estructura técnica, indexación y mejoras de rendimiento orgánico"}'
post '{"agent":"geo_specialist","name":"Especialista GEO","state":"working","task":"Trabajando visibilidad generativa, presencia semántica y señales para motores de respuesta y descubrimiento"}'
post '{"agent":"aeo_specialist","name":"Especialista AEO","state":"working","task":"Optimizando respuestas, FAQs, estructura y autoridad para aparecer en resultados de respuesta directa"}'
post '{"agent":"seo_local_specialist","name":"Especialista SEO Local","state":"working","task":"Empujando mapas, fichas, señales locales y páginas geolocalizadas para captar negocio cercano"}'
post '{"agent":"seo_entities","name":"Especialista Entidades y Autoridad","state":"working","task":"Refinando entidades, coherencia de marca, menciones y señales de autoridad digital"}'
post '{"agent":"seo_serp_intent","name":"Especialista SERP e Intención","state":"thinking","task":"Analizando intención de búsqueda, huecos de contenido y oportunidades de conversión por consulta"}'
post '{"agent":"gmb_marketing","name":"Especialista Google Business Marketing","state":"working","task":"Optimizando la ficha de Google Business de Virtual Marketing Spain con publicaciones, categorías, servicios y reseñas"}'
post '{"agent":"gmb_ia","name":"Especialista Google Business IA","state":"working","task":"Trabajando el posicionamiento local de la agencia de IA con actividad, FAQs, servicios y señales de relevancia"}'
post '{"agent":"gmb_soiz","name":"Especialista Google Business Soiz","state":"working","task":"Controlando datos, publicaciones y visibilidad local de Soiz Estampaciones en Elche"}'
post '{"agent":"gmb_terapia","name":"Especialista Google Business Terapia","state":"working","task":"Controlando publicaciones, servicios y posicionamiento local de Terapia de Masajes en Elche"}'
post '{"agent":"gmb_productos","name":"Especialista Google Business Productos Quiromasaje","state":"working","task":"Controlando la ficha, publicaciones y relevancia local de Productos Quiromasaje"}'
post '{"agent":"gmb_ginna","name":"Especialista Google Business Ginna Nails","state":"working","task":"Controlando publicaciones, servicios, reseñas y visibilidad local de Ginna Nails en Elche"}'
post '{"agent":"gmb_bike","name":"Especialista Google Business Bike Montain","state":"working","task":"Controlando publicaciones, ficha y señales locales de Bike Montain"}'
post '{"agent":"copy_senior_gmb","name":"Copywriting Senior Google Business","state":"working","task":"Supervisando publicaciones, servicios, preguntas y respuestas y textos locales para fichas de Google Business con enfoque de conversión"}'
post '{"agent":"web_dev","name":"Responsable Web","state":"working","task":"Revisando estructura de conversión, CTAs y landings clave para mejorar contacto y ventas, e implementando en virtualmarketingspain.com la plantilla optimizada de email para leads"}'
post '{"agent":"copy_senior_web","name":"Copywriting Senior Web","state":"working","task":"Supervisando titulares, propuestas de valor, secciones de venta, CTAs y textos web para que cada página convierta mejor"}'
post '{"agent":"landing_designer","name":"Diseñador Landing Pages","state":"working","task":"Preparando mejoras visuales y de conversión para páginas de venta, coordinando con web la presentación correcta del flujo de emails y llamadas"}'
post '{"agent":"automatizacion_n8n","name":"Especialista Automatización","state":"working","task":"Mapeando flujo idea-copy-imagen-publicación-reporte y conectando automatizaciones de contenido y ventas"}'
post '{"agent":"copy_senior_ai","name":"Copywriting Senior IA","state":"working","task":"Supervisando prompts comerciales, mensajes de bots, automatizaciones conversacionales y textos de IA para que sean claros, naturales y persuasivos"}'
post '{"agent":"chatbot_ai","name":"Especialista Chatbots IA","state":"working","task":"Definiendo automatizaciones conversacionales para captar y filtrar clientes"}'
post '{"agent":"social_instagram_main","name":"Especialista Instagram Principal","state":"working","task":"Preparando reel de VMS sobre automatizaciones con IA para negocios y CTA a auditoría, controlando que la automatización de publicación en n8n no falle"}'
post '{"agent":"social_instagram_ia","name":"Especialista Instagram IA","state":"working","task":"Adaptando contenido principal con enfoque técnico en ahorro de tiempo, procesos y escalabilidad, vigilando automatizaciones y duplicidades"}'
post '{"agent":"social_tiktok","name":"Especialista TikTok","state":"working","task":"Creando hooks cortos sobre por qué tu negocio pierde tiempo sin automatización y revisando que el flujo automático esté estable"}'
post '{"agent":"social_youtube_shorts","name":"Especialista YouTube Shorts","state":"working","task":"Transformando el mejor hook de TikTok en short educativo con CTA de curiosidad y verificando automatización y colas de publicación"}'
post '{"agent":"youtube_growth_research","name":"Analista Crecimiento YouTube","state":"working","task":"Analizando vídeos, shorts, títulos, miniaturas, hooks, retención y patrones de crecimiento de YouTube aplicables a VMS, Plugfy.pro, Gramflow y TPV Plugfy"}'
post '{"agent":"social_facebook_meta","name":"Especialista Facebook Meta","state":"working","task":"Preparando pieza comercial de TPV Plugfy centrada en VeriFactu y rapidez de cobro, controlando que Meta y n8n publiquen como toca"}'
post '{"agent":"social_copy_hooks","name":"Especialista Copy y Hooks","state":"thinking","task":"Escribiendo 5 hooks, 3 CTAs y variantes de copy para VMS y TPV Plugfy"}'
post '{"agent":"social_creative_design","name":"Especialista Creatividad Redes","state":"working","task":"Diseñando piezas verticales 9:16 para VMS negro-dorado y TPV Plugfy verde-negro"}'
post '{"agent":"social_viral_research","name":"Analista Viral Nicho IG/TikTok","state":"working","task":"Analizando cuentas del mismo nicho en Instagram y TikTok para detectar reels, vídeos, hooks, audios, estructuras y ángulos virales aplicables a VMS, Plugfy.pro, Gramflow y TPV Plugfy"}'
post '{"agent":"social_audio_hook_research","name":"Analista Audios y Hooks Virales","state":"working","task":"Analizando audios virales, hooks de apertura y competidores locales enfocados en empresas para detectar formatos replicables en Instagram y TikTok sin depender de seguir masivamente"}'
post '{"agent":"copy_chief","name":"Director de Copy","state":"working","task":"Revisando el mensaje final de cada publicación para asegurar claridad, gancho, tono premium y orientación comercial antes de publicar"}'
post '{"agent":"hook_specialist","name":"Especialista en Hooks","state":"working","task":"Creando aperturas que paren el scroll para Instagram, TikTok y YouTube Shorts, evitando textos genéricos y débiles"}'
post '{"agent":"caption_editor","name":"Editor de Captions","state":"working","task":"Corrigiendo ortografía, acentos, signos, codificación y limpieza final de captions para que no salgan errores raros ni textos mal escritos"}'
post '{"agent":"commercial_copy_reviewer","name":"Revisor Comercial de Copy","state":"working","task":"Validando que cada texto no solo se vea bien, sino que venda, tenga beneficio claro y llamada a la acción útil"}'
post '{"agent":"multichannel_copy_adapter","name":"Adaptador Multicanal de Copy","state":"working","task":"Adaptando el mismo mensaje a Instagram, TikTok, YouTube Shorts y Facebook sin duplicidad pobre ni pérdida de fuerza"}'
post '{"agent":"watch_vms_web","name":"Vigilancia Web VMS","state":"working","task":"Revisando 24/7 tono, claridad de oferta, autoridad, CTAs y coherencia comercial de virtualmarketingspain.com"}'
post '{"agent":"watch_tpv_web","name":"Vigilancia Web TPV","state":"working","task":"Revisando 24/7 propuesta de valor, diferenciación offline, VeriFactu, precios y fricción de compra de tpv.plugfy.pro"}'
post '{"agent":"watch_plugfy_web","name":"Vigilancia Web Plugfy.pro","state":"working","task":"Revisando 24/7 claridad de planes, promesa para agencias, percepción de producto y coherencia de automatizaciones de plugfy.pro"}'
post '{"agent":"watch_gramflow_web","name":"Vigilancia Web Gramflow","state":"working","task":"Revisando 24/7 mensaje de control, bonos, sesiones, retención y propuesta de valor de gramflow.pro"}'
post '{"agent":"watch_soiz_web","name":"Vigilancia Web Soiz","state":"working","task":"Revisando 24/7 SEO, posicionamiento, intención de compra, interacción y oportunidades de más ventas en soizestampaciones.com sin tocar la estructura"}'
post '{"agent":"watch_brand_guard","name":"Brand Guardian","state":"working","task":"Vigilando 24/7 tono de marca, duplicidades, mensajes flojos y cualquier incoherencia comercial entre marcas"}'
post '{"agent":"watch_instruction_desk","name":"Mesa de Instrucciones","state":"working","task":"Activo 24/7 esperando nuevas instrucciones del CEO y redistribuyendo prioridades al resto del equipo"}'
post '{"agent":"ads_director","name":"Director Paid Media","state":"working","task":"Definiendo estrategia de Google Ads y Meta Ads con foco en leads y rentabilidad"}'
post '{"agent":"meta_ads_strategist","name":"Estratega Meta Ads","state":"working","task":"Diseñando campañas de captación, remarketing y pruebas creativas en Meta"}'
post '{"agent":"meta_ads_creative","name":"Creativo Meta Ads","state":"working","task":"Creando ángulos y anuncios para automatización, chatbots y TPV Plugfy"}'
post '{"agent":"meta_ads_media_buyer","name":"Media Buyer Meta Ads","state":"working","task":"Preparando audiencias, presupuesto, estructura y optimización en Meta Ads"}'
post '{"agent":"google_ads_strategist","name":"Estratega Google Ads","state":"working","task":"Diseñando estructura Search y Performance Max para captar leads de alta intención"}'
post '{"agent":"google_ads_search","name":"Especialista Google Ads Search","state":"working","task":"Preparando keywords, anuncios y negativas para campañas de búsqueda"}'
post '{"agent":"google_ads_display","name":"Especialista Google Display y YouTube","state":"working","task":"Organizando remarketing visual y campañas de vídeo para audiencias calientes"}'
post '{"agent":"tracking_analytics","name":"Especialista Tracking y Analytics","state":"working","task":"Revisando píxeles, conversiones, eventos y medición de campañas"}'
post '{"agent":"cro_specialist","name":"Especialista CRO","state":"thinking","task":"Detectando mejoras en landings y funnels para subir conversión de campañas"}'
post '{"agent":"copy_senior_ads","name":"Copywriting Senior Ads","state":"working","task":"Supervisando copies de anuncios, titulares, descripciones, CTAs y ángulos de captación para Meta Ads y Google Ads"}'


post '{"agent":"seo_geo_02","name":"Especialista GEO 2","state":"working","task":"Refinando visibilidad generativa local y señales semánticas para Virtual Marketing Spain y Plugfy.pro"}'
post '{"agent":"seo_aeo_02","name":"Especialista AEO 2","state":"working","task":"Preparando FAQs, respuestas directas y estructuras orientadas a resultados de respuesta"}'
post '{"agent":"seo_local_02","name":"Especialista SEO Local 2","state":"working","task":"Refinando páginas locales, mapas y relevancia por ciudad para captar negocio cercano"}'
post '{"agent":"seo_local_03","name":"Especialista SEO Local 3","state":"working","task":"Analizando gaps de posicionamiento local para fichas y landings comerciales"}'
post '{"agent":"seo_entities_02","name":"Especialista Entidades 2","state":"working","task":"Fortaleciendo entidades, autoridad, menciones y coherencia entre webs y marcas"}'
post '{"agent":"seo_content_02","name":"Especialista SEO Contenido 2","state":"working","task":"Diseñando clusters y piezas evergreen para captación orgánica comercial"}'
post '{"agent":"seo_content_03","name":"Especialista SEO Contenido 3","state":"working","task":"Creando ideas de artículos y FAQs con intención de venta para cada marca"}'
post '{"agent":"seo_tecnico_02","name":"Especialista SEO Técnico 2","state":"working","task":"Revisando rastreo, indexación, enlazado interno y señales técnicas críticas"}'
post '{"agent":"social_instagram_growth","name":"Especialista Growth Instagram","state":"working","task":"Detectando formatos, frecuencia y acciones manuales seguras para crecimiento en Instagram"}'
post '{"agent":"social_tiktok_growth","name":"Especialista Growth TikTok","state":"working","task":"Analizando hooks, cortes, cadencia y verticales de TikTok para empresas"}'
post '{"agent":"social_reels_editor_01","name":"Editor Reels 1","state":"working","task":"Afinando estructura visual y ritmo de reels comerciales 9:16"}'
post '{"agent":"social_reels_editor_02","name":"Editor Reels 2","state":"working","task":"Preparando variantes de reels centrados en automatización, IA y chatbots"}'
post '{"agent":"social_carousel_01","name":"Especialista Carruseles 1","state":"working","task":"Creando series de carruseles educativos con CTA a auditoría"}'
post '{"agent":"social_carousel_02","name":"Especialista Carruseles 2","state":"working","task":"Preparando carruseles de SEO, GEO, AEO y automatización para empresas"}'
post '{"agent":"social_facebook_community","name":"Especialista Comunidad Facebook","state":"working","task":"Adaptando piezas y seguimiento para Facebook con ángulo más consultivo"}'
post '{"agent":"social_linkedin_b2b","name":"Especialista LinkedIn B2B","state":"working","task":"Preparando narrativa más B2B para automatizaciones, CRM y agencia 360"}'
post '{"agent":"copy_social_02","name":"Copy Social Senior 2","state":"working","task":"Refinando hooks, captions y cierres para mejorar CTR y guardados en redes"}'
post '{"agent":"copy_social_03","name":"Copy Social Senior 3","state":"working","task":"Revisando naturalidad, ortografía y tono comercial de todas las publicaciones"}'
post '{"agent":"copy_sales_02","name":"Copy Ventas Senior 2","state":"working","task":"Optimizando propuestas, secuencias de email y mensajes de seguimiento comercial"}'
post '{"agent":"copy_web_02","name":"Copy Web Senior 2","state":"working","task":"Reescribiendo propuestas de valor y CTAs para subir conversión web"}'
post '{"agent":"copy_gmb_02","name":"Copy Google Business 2","state":"working","task":"Preparando publicaciones locales, FAQs y respuestas optimizadas para fichas"}'
post '{"agent":"ventas_02","name":"Comercial Captación 2","state":"working","task":"Abriendo oportunidades con negocios de servicios y automatización"}'
post '{"agent":"ventas_03","name":"Comercial Captación 3","state":"working","task":"Empujando leads de retail, clínicas y restauración hacia auditoría"}'
post '{"agent":"ventas_04","name":"Comercial Captación 4","state":"working","task":"Preparando seguimientos de segunda y tercera interacción para leads templados"}'
post '{"agent":"ventas_05","name":"Comercial Captación 5","state":"working","task":"Filtrando oportunidades de alto ticket para IA, bots y CRM avanzado"}'
post '{"agent":"setter_02","name":"Setter de Leads 2","state":"working","task":"Calificando leads y derivando auditorías al equipo comercial"}'
post '{"agent":"setter_03","name":"Setter de Leads 3","state":"working","task":"Priorizando respuestas rápidas y manteniendo orden en las oportunidades"}'
post '{"agent":"closer_02","name":"Closer de Ventas 2","state":"working","task":"Preparando cierres consultivos para servicios de IA y automatización"}'
post '{"agent":"closer_03","name":"Closer de Ventas 3","state":"working","task":"Trabajando objeciones de precio, confianza y timing con enfoque premium"}'
post '{"agent":"auditoria_qualifier","name":"Qualificador Auditorías","state":"working","task":"Revisando si cada auditoría es real, prioritaria y con potencial comercial"}'
post '{"agent":"auditoria_followup","name":"Seguimiento Auditorías","state":"working","task":"Empujando confirmaciones, recordatorios y reactivación de auditorías pendientes"}'
post '{"agent":"gmb_vms_posts","name":"GMB VMS Publicaciones","state":"working","task":"Preparando publicaciones constantes para las dos agencias de VMS"}'
post '{"agent":"gmb_terapia_posts","name":"GMB Terapia Publicaciones","state":"working","task":"Generando ideas constantes de publicaciones locales para Terapia de Masajes"}'
post '{"agent":"gmb_soiz_posts","name":"GMB Soiz Publicaciones","state":"working","task":"Organizando publicaciones y señales de confianza para Soiz Estampaciones"}'
post '{"agent":"gmb_ginna_posts","name":"GMB Ginna Publicaciones","state":"working","task":"Preparando actividad comercial y publicaciones para Ginna Nails"}'
post '{"agent":"gmb_bike_posts","name":"GMB Bike Publicaciones","state":"working","task":"Preparando actividad y empuje de visibilidad para Bike Montain"}'
post '{"agent":"web_dev_02","name":"Web Developer 2","state":"working","task":"Mejorando estructura, bloques y claridad comercial en páginas prioritarias"}'
post '{"agent":"web_dev_03","name":"Web Developer 3","state":"working","task":"Revisando componentes reutilizables y mejoras rápidas de conversión"}'
post '{"agent":"landing_designer_02","name":"Diseñador Landing 2","state":"working","task":"Creando bloques visuales más claros para servicios de IA y TPV"}'
post '{"agent":"ux_conversion_01","name":"Especialista UX Conversión 1","state":"thinking","task":"Buscando fricciones de navegación y claridad de mensaje en las webs"}'
post '{"agent":"ux_conversion_02","name":"Especialista UX Conversión 2","state":"thinking","task":"Priorizando mejoras simples de UX que suban el contacto y la confianza"}'
post '{"agent":"automation_architect_02","name":"Arquitecto Automatización 2","state":"working","task":"Mapeando nuevas automatizaciones comerciales y de reporting sin sobrecoste"}'
post '{"agent":"automation_n8n_ops","name":"Operador n8n","state":"working","task":"Vigilando flujos, colas, publicaciones y estabilidad general de automatizaciones"}'
post '{"agent":"chatbot_ai_02","name":"Especialista Chatbots IA 2","state":"working","task":"Diseñando conversaciones más naturales para captar, filtrar y vender"}'
post '{"agent":"chatbot_ai_03","name":"Especialista Chatbots IA 3","state":"working","task":"Refinando árboles de decisión y respuestas para bots de WhatsApp y web"}'
post '{"agent":"prompt_engineer_01","name":"Prompt Engineer 1","state":"working","task":"Afinando prompts de contenido, ventas, imagen y automatización con control de costes"}'
post '{"agent":"prompt_engineer_02","name":"Prompt Engineer 2","state":"working","task":"Creando variantes de prompts para VMS, Plugfy.pro, Gramflow y TPV Plugfy"}'
post '{"agent":"meta_ads_02","name":"Meta Ads Strategist 2","state":"working","task":"Preparando pruebas de hooks y segmentos para campañas de captación"}'
post '{"agent":"meta_ads_03","name":"Meta Ads Media Buyer 2","state":"working","task":"Diseñando estructura de campañas y control de rentabilidad en Meta"}'
post '{"agent":"google_ads_02","name":"Google Ads Strategist 2","state":"working","task":"Preparando nuevas agrupaciones de intención alta para captación local"}'
post '{"agent":"google_ads_03","name":"Google Ads Search 2","state":"working","task":"Refinando anuncios, negativas y extensiones para mejorar CTR y CPL"}'
post '{"agent":"tracking_02","name":"Tracking y Analytics 2","state":"working","task":"Vigilando eventos, conversiones y señales críticas de atribución"}'
post '{"agent":"cro_02","name":"Especialista CRO 2","state":"thinking","task":"Buscando cambios pequeños de alto impacto en landings y formularios"}'
post '{"agent":"watch_social_24x7","name":"Vigilancia Redes 24/7","state":"working","task":"Controlando que la publicación automática y la calidad del contenido sigan estables"}'
post '{"agent":"watch_n8n_24x7","name":"Vigilancia n8n 24/7","state":"working","task":"Controlando errores, publicaciones, colas y automatizaciones en ejecución"}'
post '{"agent":"watch_gmb_24x7","name":"Vigilancia Google Business 24/7","state":"working","task":"Controlando actividad y consistencia de las fichas clave del ecosistema"}'
post '{"agent":"watch_sales_24x7","name":"Vigilancia Comercial 24/7","state":"working","task":"Revisando oportunidades calientes, auditorías y seguimiento crítico"}'
post '{"agent":"watch_seo_24x7","name":"Vigilancia SEO 24/7","state":"working","task":"Controlando prioridades de posicionamiento, estructura y oportunidades orgánicas"}'
post '{"agent":"ops_manager_02","name":"Manager Operaciones 2","state":"working","task":"Repartiendo carga entre equipos y detectando cuellos de botella"}'
post '{"agent":"ops_manager_03","name":"Manager Operaciones 3","state":"working","task":"Manteniendo orden, consistencia y trazabilidad entre workers y grupos"}'
post '{"agent":"reporting_daily","name":"Reporting Diario","state":"working","task":"Preparando resumen diario de ventas, captaciones, publicaciones y bloqueos"}'
post '{"agent":"reporting_weekly","name":"Reporting Semanal","state":"working","task":"Preparando estructura de reporte semanal para dirección con foco comercial"}'
post '{"agent":"research_competitors_01","name":"Analista Competencia 1","state":"working","task":"Vigilando competidores de automatización, agencias y software del nicho"}'
post '{"agent":"research_competitors_02","name":"Analista Competencia 2","state":"working","task":"Detectando mensajes, ofertas y ángulos que están funcionando en el mercado"}'

curl -s "$BASE_URL/api/agents"
echo
