#!/bin/sh
set -eu

BASE_URL="${1:-http://127.0.0.1:4322}"

post() {
  curl -s -X POST "$BASE_URL/api/heartbeat" \
    -H 'Content-Type: application/json' \
    --data-binary "$1" >/dev/null
}

post '{"agent":"director_general","name":"Director General","state":"working","task":"Dirigiendo prioridades, equipos y foco comercial de la agencia"}'
post '{"agent":"director_marketing","name":"Director de Marketing","state":"working","task":"Supervisando contenido, redes, branding y campañas de captación"}'
post '{"agent":"director_comercial","name":"Director Comercial","state":"working","task":"Coordinando captación, seguimiento, cierres y oportunidades de venta"}'
post '{"agent":"project_manager","name":"Project Manager","state":"working","task":"Controlando tareas activas, prioridades, bloqueos y entregas entre departamentos"}'
post '{"agent":"reporting_ceo","name":"Responsable Reporting CEO","state":"thinking","task":"Preparando resúmenes ejecutivos diarios, semanales y alertas de decisión"}'
post '{"agent":"performance_analyst","name":"Analista de Rendimiento","state":"thinking","task":"Midiendo resultados por marca, canal, contenido y campañas"}'
post '{"agent":"qa_procesos","name":"QA de Procesos","state":"working","task":"Revisando cumplimiento de procesos y detectando fallos operativos repetitivos"}'
post '{"agent":"cm_vms","name":"Community Manager VMS","state":"working","task":"Coordinando calendario, publicaciones y prioridades de contenido, vigilando n8n, automatizaciones y estado de publicación web/redes"}'
post '{"agent":"copy_senior_community","name":"Copywriting Senior Community","state":"working","task":"Vigilando calidad del copy en redes, hooks, captions y llamadas a la acción para cada marca"}'
post '{"agent":"ventas_01","name":"Comercial Captación","state":"working","task":"Gestionando seguimiento comercial y oportunidades de automatización"}'
post '{"agent":"copy_senior_sales","name":"Copywriting Senior Ventas","state":"working","task":"Mejorando mensajes comerciales, seguimientos y propuestas para subir respuesta y cierre"}'
post '{"agent":"setter_leads","name":"Setter de Leads","state":"working","task":"Clasificando leads entrantes y preparando primeros contactos comerciales"}'
post '{"agent":"closer_ventas","name":"Closer de Ventas","state":"working","task":"Preparando cierres y objeciones para propuestas de automatización y marketing"}'
post '{"agent":"audit_intake_manager","name":"Responsable Auditorías","state":"working","task":"Recibiendo solicitudes de auditoría, ordenando prioridades y moviendo cada caso a seguimiento claro"}'
post '{"agent":"audit_calendar_coordinator","name":"Coordinador Google Calendar Auditorías","state":"working","task":"Manteniendo la lógica de agenda para auditorías y su visibilidad interna"}'
post '{"agent":"audit_sheet_manager","name":"Gestor Sheet Auditorías","state":"working","task":"Manteniendo una hoja maestra con auditorías, origen, estado y próximos pasos"}'
post '{"agent":"audit_email_notifier","name":"Notificador Email Auditorías","state":"working","task":"Manteniendo avisos automáticos por email cuando entra o cambia una auditoría"}'
post '{"agent":"ventas_whatsapp","name":"Comercial WhatsApp","state":"working","task":"Gestionando secuencias de WhatsApp y seguimiento rápido de leads templados"}'
post '{"agent":"ventas_email","name":"Comercial Email Outbound","state":"working","task":"Gestionando secuencias de email outbound y seguimiento a leads con correo válido, revisando con web la plantilla activa"}'
post '{"agent":"ventas_sector_restauracion","name":"Comercial Restauración","state":"working","task":"Prospectando restaurantes, bares y cafeterías con enfoque en más reservas, reseñas y automatización"}'
post '{"agent":"ventas_sector_estetica","name":"Comercial Estética y Salud","state":"working","task":"Prospectando estética, uñas, terapias y clínicas con foco en más citas y seguimiento automatizado"}'
post '{"agent":"ventas_sector_retail","name":"Comercial Retail y Tiendas","state":"working","task":"Prospectando retail y comercio local con foco en TPV, visibilidad y captación"}'
post '{"agent":"ventas_propuestas","name":"Especialista Propuestas Comerciales","state":"working","task":"Traduciendo oportunidades en propuestas, presupuestos y cierres claros"}'
post '{"agent":"seo_lead","name":"SEO Lead","state":"thinking","task":"Analizando mejoras SEO, GEO y AEO en webs y servicios clave"}'
post '{"agent":"copy_senior_seo","name":"Copywriting Senior SEO","state":"working","task":"Revisando copy SEO, FAQs, títulos y textos para que posicionen mejor y conviertan mejor"}'
post '{"agent":"seo_content","name":"Especialista SEO Contenido","state":"working","task":"Proponiendo contenidos orientados a posicionamiento, intención y captación"}'
post '{"agent":"seo_tecnico","name":"Especialista SEO Técnico","state":"working","task":"Revisando estructura, indexación, rendimiento y mejoras técnicas clave"}'
post '{"agent":"geo_specialist","name":"Especialista GEO","state":"working","task":"Monitorizando visibilidad generativa y señales para buscadores con respuesta asistida"}'
post '{"agent":"aeo_specialist","name":"Especialista AEO","state":"working","task":"Monitorizando FAQs, respuestas directas, estructura y oportunidad de aparecer en resultados enriquecidos"}'
post '{"agent":"seo_local_specialist","name":"Especialista SEO Local","state":"working","task":"Monitorizando señales locales, mapas, ciudades y captación de negocio cercano"}'
post '{"agent":"seo_entities","name":"Especialista Entidades y Autoridad","state":"working","task":"Monitorizando coherencia de entidades, marca y señales de autoridad"}'
post '{"agent":"seo_serp_intent","name":"Especialista SERP e Intención","state":"thinking","task":"Monitorizando intención de búsqueda y oportunidades de contenido con impacto comercial"}'
post '{"agent":"gmb_marketing","name":"Especialista Google Business Marketing","state":"working","task":"Optimizando Google Business Profile de la agencia de marketing con publicaciones, servicios, reseñas y SEO local"}'
post '{"agent":"gmb_ia","name":"Especialista Google Business IA","state":"working","task":"Optimizando Google Business Profile de la agencia de IA con autoridad local, categorías, FAQs y actividad constante"}'
post '{"agent":"gmb_soiz","name":"Especialista Google Business Soiz","state":"working","task":"Monitorizando ficha, publicaciones y posicionamiento local de Soiz Estampaciones"}'
post '{"agent":"gmb_terapia","name":"Especialista Google Business Terapia","state":"working","task":"Monitorizando ficha, publicaciones, servicios y relevancia local de Terapia de Masajes"}'
post '{"agent":"gmb_productos","name":"Especialista Google Business Productos Quiromasaje","state":"working","task":"Monitorizando ficha, productos, publicaciones y señales locales de Productos Quiromasaje"}'
post '{"agent":"gmb_ginna","name":"Especialista Google Business Ginna Nails","state":"working","task":"Monitorizando ficha, publicaciones, reseñas y visibilidad local de Ginna Nails"}'
post '{"agent":"gmb_bike","name":"Especialista Google Business Bike Montain","state":"working","task":"Monitorizando ficha, publicaciones y autoridad local de Bike Montain"}'
post '{"agent":"copy_senior_gmb","name":"Copywriting Senior Google Business","state":"working","task":"Revisando textos de publicaciones y mensajes locales para fichas de Google Business"}'
post '{"agent":"web_dev","name":"Responsable Web","state":"working","task":"Revisando landings, CTAs y mejoras de conversión, y manteniendo implementada la plantilla optimizada de email en virtualmarketingspain.com"}'
post '{"agent":"copy_senior_web","name":"Copywriting Senior Web","state":"working","task":"Vigilando titulares, CTAs, propuestas de valor y textos de venta de las webs"}'
post '{"agent":"landing_designer","name":"Diseñador Landing Pages","state":"working","task":"Preparando mejoras visuales y de conversión para páginas de venta, cuidando la presentación del flujo de emails y llamadas"}'
post '{"agent":"automatizacion_n8n","name":"Especialista Automatización","state":"working","task":"Manteniendo flujos de automatización, contenido y reporting"}'
post '{"agent":"copy_senior_ai","name":"Copywriting Senior IA","state":"working","task":"Revisando mensajes de bots, prompts comerciales y automatizaciones conversacionales para que sean naturales y efectivos"}'
post '{"agent":"chatbot_ai","name":"Especialista Chatbots IA","state":"working","task":"Diseñando automatizaciones conversacionales para captación y atención"}'
post '{"agent":"social_instagram_main","name":"Especialista Instagram Principal","state":"working","task":"Preparando reels y publicaciones comerciales para la cuenta principal y revisando que n8n esté publicando sin errores"}'
post '{"agent":"social_instagram_ia","name":"Especialista Instagram IA","state":"working","task":"Adaptando contenidos de IA con enfoque técnico y sin duplicidad, vigilando automatización y cola de contenidos"}'
post '{"agent":"social_tiktok","name":"Especialista TikTok","state":"working","task":"Creando hooks y piezas verticales de alto alcance y controlando estabilidad del flujo automático"}'
post '{"agent":"social_youtube_shorts","name":"Especialista YouTube Shorts","state":"working","task":"Transformando ideas en shorts educativos y comerciales, revisando publicación automatizada"}'
post '{"agent":"youtube_growth_research","name":"Analista Crecimiento YouTube","state":"working","task":"Vigilando vídeos y shorts de YouTube para detectar títulos, hooks, retención, miniaturas y estructuras que ayuden a crecer"}'
post '{"agent":"social_facebook_meta","name":"Especialista Facebook Meta","state":"working","task":"Gestionando publicaciones y calendario en Meta Business Suite, vigilando n8n y la salida automática"}'
post '{"agent":"social_copy_hooks","name":"Especialista Copy y Hooks","state":"thinking","task":"Escribiendo hooks, copies y CTAs para captar atención y leads"}'
post '{"agent":"social_creative_design","name":"Especialista Creatividad Redes","state":"working","task":"Diseñando creatividades 9:16 por marca y objetivo"}'
post '{"agent":"social_viral_research","name":"Analista Viral Nicho IG/TikTok","state":"working","task":"Vigilando cuentas del mismo nicho en Instagram y TikTok para detectar virales, patrones de retención, hooks, audios y formatos replicables"}'
post '{"agent":"social_audio_hook_research","name":"Analista Audios y Hooks Virales","state":"working","task":"Vigilando audios virales, hooks de apertura y competidores locales orientados a empresas para detectar ideas reutilizables en Instagram y TikTok"}'
post '{"agent":"copy_chief","name":"Director de Copy","state":"working","task":"Supervisando el mensaje final y la calidad del copy antes de cada publicación"}'
post '{"agent":"hook_specialist","name":"Especialista en Hooks","state":"working","task":"Probando hooks, aperturas y primeras frases que mejoran retención y clic"}'
post '{"agent":"caption_editor","name":"Editor de Captions","state":"working","task":"Revisando ortografía, acentos, codificación y limpieza de captions antes de que salgan publicados"}'
post '{"agent":"commercial_copy_reviewer","name":"Revisor Comercial de Copy","state":"working","task":"Comprobando que el texto tenga beneficio claro, foco de venta y CTA útil"}'
post '{"agent":"multichannel_copy_adapter","name":"Adaptador Multicanal de Copy","state":"working","task":"Ajustando cada copy al canal correcto para evitar duplicidades flojas entre Instagram, TikTok, YouTube y Facebook"}'
post '{"agent":"watch_vms_web","name":"Vigilancia Web VMS","state":"working","task":"Monitorizando virtualmarketingspain.com para detectar mejoras de tono, oferta, CTA y conversión"}'
post '{"agent":"watch_tpv_web","name":"Vigilancia Web TPV","state":"working","task":"Monitorizando tpv.plugfy.pro para reforzar el mensaje de venta sin internet, VeriFactu y compra inmediata"}'
post '{"agent":"watch_plugfy_web","name":"Vigilancia Web Plugfy.pro","state":"working","task":"Monitorizando plugfy.pro para vigilar planes, claridad comercial y percepción de herramienta para agencias"}'
post '{"agent":"watch_gramflow_web","name":"Vigilancia Web Gramflow","state":"working","task":"Monitorizando gramflow.pro para vigilar retención, orden, bonos y experiencia de cliente"}'
post '{"agent":"watch_soiz_web","name":"Vigilancia Web Soiz","state":"working","task":"Monitorizando soizestampaciones.com para detectar mejoras SEO, posicionamiento comercial e interacción sin tocar estructura"}'
post '{"agent":"watch_brand_guard","name":"Brand Guardian","state":"working","task":"Vigilando tono, consistencia, promesas, duplicidades y mensajes débiles en todas las marcas"}'
post '{"agent":"watch_instruction_desk","name":"Mesa de Instrucciones","state":"working","task":"Activo 24/7 en espera de instrucciones del CEO, bloqueos y prioridades nuevas"}'
post '{"agent":"ads_director","name":"Director Paid Media","state":"working","task":"Supervisando estrategia, presupuesto, rendimiento y escalado de campañas"}'
post '{"agent":"meta_ads_strategist","name":"Estratega Meta Ads","state":"working","task":"Definiendo campañas de captación, remarketing y pruebas creativas en Meta"}'
post '{"agent":"meta_ads_creative","name":"Creativo Meta Ads","state":"working","task":"Preparando ángulos, anuncios y variaciones creativas para campañas de Meta"}'
post '{"agent":"meta_ads_media_buyer","name":"Media Buyer Meta Ads","state":"working","task":"Gestionando conjuntos de anuncios, audiencias, presupuesto y optimización"}'
post '{"agent":"google_ads_strategist","name":"Estratega Google Ads","state":"working","task":"Diseñando campañas Search, Performance Max y remarketing orientadas a leads"}'
post '{"agent":"google_ads_search","name":"Especialista Google Ads Search","state":"working","task":"Preparando grupos de anuncios, keywords, negativas y copys de búsqueda"}'
post '{"agent":"google_ads_display","name":"Especialista Google Display y YouTube","state":"working","task":"Organizando remarketing visual y vídeo para audiencias calientes"}'
post '{"agent":"tracking_analytics","name":"Especialista Tracking y Analytics","state":"working","task":"Revisando píxeles, conversiones, eventos, UTMs y medición de campañas"}'
post '{"agent":"cro_specialist","name":"Especialista CRO","state":"thinking","task":"Analizando qué cambios aumentan la conversión de campañas y landings"}'
post '{"agent":"copy_senior_ads","name":"Copywriting Senior Ads","state":"working","task":"Revisando copies de anuncios, ángulos, titulares y CTAs para mejorar rendimiento de campañas"}'
